services:
  - type: web
    name: frontend
    env: node

    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "npx serve -s frontend/build"
    branch: main

  - type: web
    name: backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    plan: free
    branch: main

  - type: web
    name: socket
    env: node
    buildCommand: "cd socket && npm install"
    startCommand: "cd socket && npm start"
    plan: free
    branch: main
