services:
  - type: static
    name: frontend
    buildCommand: "cd frontend && npm install && npm run build"
    publishPath: "frontend/build"
    plan: free
    branch: main

  - type: web
    name: backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    plan: free
    branch: main

  - type: web
    name: socket
    env: node
    buildCommand: "cd socket && npm install"
    startCommand: "cd socket && npm start"
    plan: free
    branch: main
